Repository nginxinc/ansible-role-nginx-app-protect, pull requests merged in 2021-09, with the labels that each got.

#128 Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#129 Fix release drafter template link text
  .github/release-drafter.yml
Labels: bug, documentation, skip-changelog

#130 Remove Debian Stretch from supported platforms and temporarily install NGINX Plus R24 in Molecule tests
  CHANGELOG.md
  README.md
  meta/main.yml
  molecule/advanced/prepare.yml
  molecule/advanced/requirements.yml
  molecule/default/molecule.yml
  molecule/default/prepare.yml
  molecule/default/requirements.yml
  molecule/dos/prepare.yml
  molecule/dos/requirements.yml
  molecule/specific-version/molecule.yml
  molecule/specific-version/prepare.yml
  molecule/specific-version/requirements.yml
  vars/main.yml
Labels: bug
