Repository nginxinc/ansible-role-nginx-app-protect, pull requests merged in 2021-07, with the labels that each got.

#110 nginx_app_protect_manage_repo flag for RHEL NGINX Plus repository
  tasks/install/install-redhat.yml
Labels: bug

#111 Add support for NGINX App Protect DoS module
  .github/workflows/molecule.yml
  CHANGELOG.md
  README.md
  defaults/main.yml
  meta/main.yml
  molecule/advanced/converge.yml
  molecule/advanced/verify.yml
  molecule/default/converge.yml
  molecule/default/verify.yml
  molecule/dos/converge.yml
  molecule/dos/molecule.yml
  molecule/dos/prepare.yml
  molecule/dos/requirements.yml
  molecule/dos/verify.yml
  molecule/specific-version/converge.yml
  molecule/specific-version/molecule.yml
  molecule/specific-version/verify.yml
  tasks/common/install/remove-license.yml
  tasks/common/install/service-modification.yml
  tasks/common/install/setup-license.yml
  tasks/common/keys/setup-keys.yml
  tasks/common/prerequisites/install-dependencies.yml
  tasks/common/prerequisites/validate-supported-os.yml
  tasks/dos/install/install-app-protect-dos.yml
  tasks/dos/install/install-debian.yml
  tasks/dos/install/install-redhat.yml
  tasks/main.yml
  tasks/waf/config/configure-app-protect-waf.yml
  tasks/waf/install/install-alpine.yml
  tasks/waf/install/install-app-protect-waf.yml
  tasks/waf/install/install-debian.yml
  tasks/waf/install/install-redhat.yml
  vars/main.yml
Labels: enhancement, feature

#112 NAP 3.3 updates
  CHANGELOG.md
  README.md
  molecule/Dockerfile.j2
  molecule/advanced/molecule.yml
  molecule/advanced/prepare.yml
  molecule/default/molecule.yml
  molecule/default/prepare.yml
  molecule/default/verify.yml
  molecule/specific-version/molecule.yml
  molecule/specific-version/prepare.yml
  tasks/common/keys/setup-keys.yml
  tasks/common/prerequisites/install-dependencies.yml
  tasks/common/prerequisites/validate-supported-os.yml
  tasks/waf/install/install-redhat.yml
  vars/main.yml
Labels: feature

#113 Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies, enhancement
