Repository nginxinc/ansible-role-nginx-app-protect, pull requests merged in 2021-04, with the labels that each got.

#76 Nap 31 updates
  CHANGELOG.md
  README.md
  meta/main.yml
  molecule/advanced/molecule.yml
  molecule/default/molecule.yml
  molecule/specific-version/molecule.yml
  vars/main.yml
Labels: feature

#81 Update Ansible collections
  .github/workflows/molecule.yml
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
Labels: dependencies, enhancement

#82 Change default NGINX App Protect conf path for 3.2
  CHANGELOG.md
  defaults/main.yml
  molecule/default/verify.yml
Labels: enhancement

#83 Implement Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  CHANGELOG.md
Labels: feature

#84 Update Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies, documentation
