Repository nginxinc/ansible-role-nginx-app-protect, pull requests merged in 2021-06, with the labels that each got.

#100 Replace Ansible base with Ansible core
  .github/workflows/requirements/requirements_galaxy.txt
  .github/workflows/requirements/requirements_molecule.txt
  CHANGELOG.md
  README.md
Labels: dependencies, enhancement

#104 Bump Ansible collections
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#103 Replace "yes"/"no" boolean values with "true"/"false"
  .ansible-lint
  .github/workflows/galaxy.yml
  .github/workflows/molecule.yml
  .github/workflows/release-drafter.yml
  .yamllint
  CHANGELOG.md
  tasks/install/install-debian.yml
Labels: enhancement

#107 Update `nginx` role requirement in Molecule tests to `0.20.0`
  .ansible-lint
  CHANGELOG.md
  molecule/advanced/requirements.yml
  molecule/default/requirements.yml
  molecule/specific-version/molecule.yml
  molecule/specific-version/requirements.yml
Labels: dependencies

#108 Add 'nginx_app_protect_manage_repo' feature flag and defaults
  CHANGELOG.md
  defaults/main.yml
  tasks/install/install-alpine.yml
  tasks/install/install-debian.yml
  tasks/install/install-redhat.yml
Labels: feature
