Repository nginxinc/ansible-role-nginx-app-protect, pull requests merged in 2022-04, with the labels that each got.

#178 Set timeout for service starts
  CHANGELOG.md
  templates/nginx.service.override.conf.j2
Labels: enhancement

#180 Add support for enabling SELinux on RHEL based systems
  CHANGELOG.md
  README.md
  defaults/main.yml
  molecule/advanced/converge.yml
  molecule/default/converge.yml
  tasks/common/install/service-modification.yml
  tasks/common/prerequisites/install-dependencies.yml
  tasks/common/prerequisites/prerequisites.yml
  tasks/common/prerequisites/setup-selinux.yml
  tasks/main.yml
  templates/selinux/nginx-app-protect-module.te.j2
  templates/services/nginx.service.override.conf.j2
Labels: enhancement, feature

#181 Bump `community.docker` collection
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies

#182 Add `TimeoutStartSec` parameter
  CHANGELOG.md
  defaults/main.yml
  molecule/advanced/converge.yml
  templates/services/nginx.service.override.conf.j2
Labels: enhancement, breaking change

#183 Bump `community.docker` collection
  .github/workflows/requirements/requirements_ansible.yml
  CHANGELOG.md
  README.md
Labels: dependencies
